### ISSUE TITLE
Midi selection button in framed mode

### ISSUE THREAD

**Issue by puhoshville** [drahoslove/pianco#47]
@drahoslove hello! thanks again for your project!
I'm encountering an issue with framed mode (isFramed == true).
My goal right now – it's get midi selection buttons in framed mode. Exactly the same buttons as in default mode. 
I don't know how, but they just disappeared in framed mode.
Thanks in advance!

**Comment by puhoshville** [comment]
some additional info. we are trying to solve this issue in this fork https://github.com/puhoshville/pianco

**Comment by drahoslove** [comment]
Hi. It's hidden using css.
Just remove this line and it should work for you
https://github.com/puhoshville/pianco/blob/master/css/main.css#L1463

**Comment by lShinal** [comment]
@drahoslove 
we have commented out this line in the css, but the midi button is still not displayed. 
We have also commented this line -
[https://github.com/drahoslove/pianco/blob/377b8e1827a6f42eab20455139906ea80774a8ea/index.html#L516](url)
This also has no effect.
In the iframe itself, we additionally pass the allow attribute with the following parameters 'autoplay; fullscreen; encrypted-media; picture-in-picture; midi; usb;'
The strange thing is that if we remove 'midi' from allow attribute, the icon itself appears, but when hovering over it, it says "MIDI in: failed"

**Comment by drahoslove** [comment]
That's strange.
You need the `midi` attribute to be able to use the midi functionality in frame, but it should not have an effect on the button itself.

Do you actually need the framed mode to behave any differently?
If not, the easiest solution for you would probably be to just replace the `const isFramed = window.parent !== window` by `const isFramed = false` (there are several places where it is defined)

**Comment by puhoshville** [comment]
sorry for late response! issue resolved! the main reason was not really good implementation on our side! thanks for your comment!
